### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Etherll** [FFFFFFFXXXXXXX/league_record#1]
seems like the app is crashing 

- windows 11

**Comment by FFFFFFFXXXXXXX** [comment]
Well, what version did you download? Have you tried the .msi installer? Are there any error messages?

**Comment by FFFFFFFXXXXXXX** [comment]
I assume the problem was that you were using the zipped version without installing the Webview2 runtime. The installer installs that runtime if it is missing :)
