### ISSUE TITLE
Void grubs- recorder crashing

### ISSUE THREAD

**Issue by judehek** [FFFFFFFXXXXXXX/league_record#10]
It seems like when a void grub kill event is triggered the recorder shuts down?

**Comment by FFFFFFFXXXXXXX** [comment]
I feared something like that, I haven't had time to adjust the app to the new map.

I'll try to fix it as soon as possible

**Comment by FFFFFFFXXXXXXX** [comment]
Alright, [release 1.15.2](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.15.2) should fix the issue

**Comment by judehek** [comment]
yep- just tested, thanks for the quick turnaround!
