### ISSUE TITLE
videos don't show any info

### ISSUE THREAD

**Issue by danolloxd** [FFFFFFFXXXXXXX/league_record#12]
![image](https://github.com/FFFFFFFXXXXXXX/league_record/assets/40907197/d3f308f7-ffc1-49aa-80d8-1a426828d7af)

all videos look like this, 0/0 statline with no champ identifier (idk if the champ part was ever a thing)

**Comment by FFFFFFFXXXXXXX** [comment]
Thanks for the issue, could you set `"debugLog":true` in the settings and post the logs from the `%APPDATA%/fx.LeagueRecord/logs/`.

**Comment by danolloxd** [comment]
[2024-01-17_16-54.log](https://github.com/FFFFFFFXXXXXXX/league_record/files/13975877/2024-01-17_16-54.log)

**Comment by FFFFFFFXXXXXXX** [comment]
Actually I released a quick fix: https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.15.5
Does that fix the issue?

**Comment by danolloxd** [comment]
v1.15.5 fixed the issue - thanks!
