### ISSUE TITLE
~1/10ish games not recording

### ISSUE THREAD

**Issue by judehek** [FFFFFFFXXXXXXX/league_record#13]
hey, I've been playing a lot, and I noticed strangely that roughly 10% of games don't record. I tried to replicate with debug in practice tool and I found out that sometimes it falsely detects the game as a spectator game and the recorder shuts down. any ideas on this? not the end of the world but can be annoying

**Comment by FFFFFFFXXXXXXX** [comment]
Yeah, I am aware about that bug, it's really annoying.
I didn't have a way to reproduce it until finally added some proper logging last week.
But I am now working on a fix.

**Comment by FFFFFFFXXXXXXX** [comment]
I am pretty sure [release 1.16.1](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.16.1) should fix the issue.

**Comment by FFFFFFFXXXXXXX** [comment]
The issue is that sometimes the ingame API reports that a game is a spectator game even though it isn't. I think it is some weird race condition where the API has started but some settings or configuration are not fully loaded yet.
I hope there are no weird edge cases I missed.

**Comment by judehek** [comment]
seems working so far, thanks!
