### ISSUE TITLE
outputResolution not present by default in settings.

### ISSUE THREAD

**Issue by ceselder** [FFFFFFFXXXXXXX/league_record#19]
![image](https://github.com/FFFFFFFXXXXXXX/league_record/assets/94973748/9189b2e7-6436-4ac0-9721-57253d21258e)

If I try adding it, my settings reset aswell (I think). Anyone can reproduce?

**Comment by FFFFFFFXXXXXXX** [comment]
It 'resets' if the value is invalid.
`"outputResolution": "1280x720p",` works for me.

**Comment by ceselder** [comment]
Will try!

**Comment by FFFFFFFXXXXXXX** [comment]
did it work / can I close this issue?

**Comment by FFFFFFFXXXXXXX** [comment]
fixed by v1.19.0
