### ISSUE TITLE
Flickering scrollbar on  fullscreen 

### ISSUE THREAD

**Issue by Etherll** [FFFFFFFXXXXXXX/league_record#2]
When i open the app as fullscreen the scrollbar flickering .
here a example:
![z9DxmvJ - Imgur](https://user-images.githubusercontent.com/61019402/167818578-1d73a167-4e0a-4fed-8e0b-760e27e3b697.gif)

**Comment by FFFFFFFXXXXXXX** [comment]
Version 1.3.3 should have that fixed.
