### ISSUE TITLE
[BUG] Last 2 games have recorded loading screen and mouse movement for some reason

### ISSUE THREAD

**Issue by ceselder** [FFFFFFFXXXXXXX/league_record#21]
![image](https://github.com/FFFFFFFXXXXXXX/league_record/assets/94973748/b810ef3b-1e1b-4319-8439-edae4aa2b7db)

**Comment by FFFFFFFXXXXXXX** [comment]
So the whole recording is just the loading screen with mouse movement?

**Comment by ceselder** [comment]
Yes exactly. I am testing now if it was due to an interaction with rivatuner

**Comment by ceselder** [comment]
Was an interaction with rivatuner I believe. Problem is resolved after simply closing rivatuner.
