### ISSUE TITLE
[bug] "no data" when finishing game with the webview open

### ISSUE THREAD

**Issue by ceselder** [FFFFFFFXXXXXXX/league_record#22]
Will reliably show "no data" when finishing ranked games if leaguerecord was open but not in tray. IF it is in tray it behaves as expected.

I know you've been tracking down this bug for a while (I think)? So I hope this helps.

**Comment by FFFFFFFXXXXXXX** [comment]
Since you mentioned ranked games specifically, is the behaviour different for non-ranked games?

**Comment by ceselder** [comment]
I think it might be specific to ranked games yes. The metadata never shows up however.

**Comment by FFFFFFFXXXXXXX** [comment]
Please enable logs in the settings and post them if it happens again.

I haven't found away to replicate the bug yet.

**Comment by FFFFFFFXXXXXXX** [comment]
fixed in [v1.19.2](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.19.2)

**Comment by ceselder** [comment]
Thank you so much! What did the bug end up being? (dw if its too logn to explain or you cba)

**Comment by FFFFFFFXXXXXXX** [comment]
It was something stupid.
I was parsing/deserializing the current_gold of the players in the timeline-data to a u64, but it can be negative when a player uses the futures market rune.

I'm fairly sure players are way more likely to use futues market in ranked and this was the problem and not the ranked gamemode.

**Comment by FFFFFFFXXXXXXX** [comment]
It was something stupid.
I was parsing/deserializing the current_gold of the players in the timeline-data to a u64, but it can be negative when a player uses the futures market rune.

I'm think players are way more likely to use futues market in ranked and this was the problem, not the ranked gamemode. And the window open/closed was just coincidental.
But feel free to re-open the issue if I'm wrong and the issue still persists.

**Comment by ceselder** [comment]
incredible, thats really funny. Thanks for fixing it
