### ISSUE TITLE
Question and Feature suggestion.

### ISSUE THREAD

**Issue by QiyanuReeves** [FFFFFFFXXXXXXX/league_record#29]
Hello,

I've been using your software, which has quickly become my favourite. I have a few suggestions that I hope you can consider:

Could you please introduce the playback speed option (if I remember it had one)

Whenever I click delete, I receive a prompt asking if I want to "Delete Recording: Example." It would be great to have a setting to disable this notification.

What is the WS, is it Vision Score?

Additionally, could you make the progress bar larger and adjust the size and colour of the event indicators? (Or add a setting which makes us put them to our liking)

Thank you very much.

**Comment by FFFFFFFXXXXXXX** [comment]
Hi, nice to hear that this project is useful.

The playback speed option should still be there (I checked versions 1.19.3 and 1.19.4):
![grafik](https://github.com/user-attachments/assets/275fe09d-f001-49d3-9495-3cbf61b44441)

For the delete prompt I could add a checkbox that says: "dont ask me again" or something. Would that work?

WS = Ward Score which is the same as Vision Score

As for the markers, what exactly is the problem/difficulty when using them and what would you change if you could adjust them in any way?
I'm interested in what the root problem is, so I can consider different ways of solving the problem.

**Comment by QiyanuReeves** [comment]
Sorry for answering so late, I was busy with my job, as it is summer and the hotel I work at is full.

The playback speed option is indeed there. Perhaps I hadn't noticed it all this time. 🤦

Yeah, the "Don't ask me again" checkbox would work and is better.

The markers aren't a problem; they're more like a useful change. I'm using a laptop with a small screen, so the markers are automatically small. I would change the size of the progress bar to my liking, and based on the size of the bar, the markers also get bigger alongside it.

**Comment by FFFFFFFXXXXXXX** [comment]
No problem, here's where I am currently at:

There is indeed a bug, where the playback-speed button disappears after deleting a video, because I was resetting the video-player incorrectly, will be fixed in v2.

I am happy with the "don't ask me again" checkbox as a solution to the problem, will also be in v2.

The video-player UI will simply be bigger in v2 but not user-adjustable. If it is still not big/usable enough I will re-consider.
So please let me know when I release v2!

**Comment by FFFFFFFXXXXXXX** [comment]
v2.0.0 is out now
