### ISSUE TITLE
question about old gameplays.

### ISSUE THREAD

**Issue by ghost** [FFFFFFFXXXXXXX/league_record#30]
hello really great program thanks you, I love using it, there are games I played 1-2 days ago, so I can download and watch the replay from the lol client since its on same patch, is there any way to transfer them to leaguerecord?

**Comment by FFFFFFFXXXXXXX** [comment]
no, the app currently does not have a way to do this

**Comment by FFFFFFFXXXXXXX** [comment]
I could add a feature to record replays - and you would have to run the whole replay at speed 1x but you wouldnt be able to see your mousecursor.

The main reason I have not added this is bevause the timestamps go out of sync with the video as soon as you change the replay speed or jump around in the replay timeline.
