### ISSUE TITLE
Audio recording issues

### ISSUE THREAD

**Issue by judehek** [FFFFFFFXXXXXXX/league_record#32]
hey again, thanks for your hard work as always! sometimes I play using bluetooth, and my friend and I have noticed issues when playing with a bluetooth device. for me, it just makes the audio quality much lower and max volume. for him, he says his entire audio fully cuts out. here are my logs: 
[2024-10-06_13-42.log](https://github.com/user-attachments/files/17270742/2024-10-06_13-42.log)

for both of us, there's an immediate audio change when the game window opens, and then it returns to normal ~10 seconds after the game window closes. was happening on v1 as well, pretty sure it's an issue with the recorder. thanks!

**Comment by FFFFFFFXXXXXXX** [comment]
At a first glance this reminds me of this issue: https://obsproject.com/forum/threads/no-sound-through-bluetooth-headphones-when-obs-starts.107276/post-407981

Basically your default audio input and output devices are set to your bluetooth device. And as soon as the OS demands a microphone and a headphone connection from the bluetooth device at the same time, it splits its limited bandwidth (one part for audio input, one for output) which results in lower audio quality.

If this is actually whats going on and you set your laptops default audio input device to some other microphone (e.g. the one built into your laptop) the problem *should* go away.

**Comment by judehek** [comment]
hm, didn't seem to work. although, it could be on my end. windows 11 doesn't seem to have a dedicated "default" feature like windows 10 (see screenshot):
![Screenshot 2024-10-07 194514](https://github.com/user-attachments/assets/00559d60-30d3-470e-a78e-5dca6b91c7d4)

instead, as you can see, I just set the input device to the other one. the issue still persisted though. I also looked online for setting default, but I couldn't find anything.

**Comment by judehek** [comment]
works! thanks as always!
