### ISSUE TITLE
video goes black when i alt +tab from game

### ISSUE THREAD

**Issue by Etherll** [FFFFFFFXXXXXXX/league_record#4]
yea like the title says video goes black when I alt +tab from game for some reasons

**Comment by FFFFFFFXXXXXXX** [comment]
Do you mean the recording is a black screen during the period where you are tabbed out of the game?

**Comment by Etherll** [comment]
Yes

**Comment by FFFFFFFXXXXXXX** [comment]
That is a limitation of libobs so I cant really do anything about that. Switching from "Full Screen" mode to "Borderless" in the LoL ingame settings fixes this issue.
