### ISSUE TITLE
Feature request record mic audio

### ISSUE THREAD

**Issue by AKL55** [FFFFFFFXXXXXXX/league_record#5]
Add an option to record mic audio.

Thanks for making league_record. i have been using a lot lately.

**Comment by FFFFFFFXXXXXXX** [comment]
I have a test build that you can try. If you set "recordAudio": "ALL" in the settings it should record the system audio (everything you hear) and your default mic input.

https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.13.1-alpha

Let me know if it works for you or there are some improvements I could make.

**Comment by FFFFFFFXXXXXXX** [comment]
Did you by chance get to test the demo yet? Did everything work as intended? Any improvements I could make?

**Comment by AKL55** [comment]
Worked really well. About improvements, the only thing that i can think is to maybe add AV1 hardware encoding,
I always reencode using software encoding after so that's not really that important for me honestly.
