### ISSUE TITLE
Game recording isnt working properly

### ISSUE THREAD

**Issue by J4nniK** [FFFFFFFXXXXXXX/league_record#6]
For some reason I am not able to properly record any games with the software
https://i.imgur.com/7KxpaEM.png

As you can see in the link above, the software is recording something but if I open the file the only thing that seems to get recorded is the audio and no video.

Do you have any idea on how I can fix this?

Hardware and Software information:

Software: 
OS: Windows 10 Pro Version 10.0.19045 Build 19045

Hardware:
GPU: AMD Radeon RX 6750XT with driver software version 23.3.2 minimal setup (so just drivers without the software center)
CPU: Ryzen 7 5800X3D

**Comment by FFFFFFFXXXXXXX** [comment]
Could you run `LeagueRecord.exe -d | echo` in the cmdline from where the software is installed on your PC and then try to record a game (practicetool or sth).

Maybe that could give me a hint as to whats going wrong.

**Comment by FFFFFFFXXXXXXX** [comment]
Also did a previous version work? Did the same version work but now it doesn't anymore?

**Comment by J4nniK** [comment]
> Could you run `LeagueRecord.exe -d | echo` in the commandline from where the software is installed on your PC

Yes for sure!
So my executable is stored in the path that you mentioned.
I started my commandline in administrator mode and executed your command and then started a practice tool game, as it seems the console doesnt give any further output:
https://i.imgur.com/d7HiWxS.jpeg

> Also did a previous version work? Did the same version work but now it doesn't anymore?
I can't answer this question because this is the first version of the software that I installed on my computer.
I only know that a friend of mine is using the same version and its working for him.

**Comment by FFFFFFFXXXXXXX** [comment]
Ah sorry I forgot to mention to use powershell as the commandline. I didnt know the cmd 'echo' command works differently from the powershell one.

The output should look something like the following and continue to print stuff while the software is running

```
PS C:\Program Files\LeagueRecord> .\LeagueRecord.exe -d | echo
LeagueRecord v1.14.1
debug_log: enabled

Settings: Settings(RwLock { ... })

Checking for update: 1.14.1/1.14.1 (current/newest)

saved window size: 1200x650.4
saved window position: 424x 250.4y
video folder: "C:\\Users\\USERNAME\\Videos\\league_recordings"

fileserver port: 49152

...
```

**Comment by J4nniK** [comment]
No problem.
So I started the command in powershell and I am getting the following output:

https://i.imgur.com/EyawHaD.png

**Comment by J4nniK** [comment]
No problem its all fine! 
I m super happy to test the new release once its up

**Comment by FFFFFFFXXXXXXX** [comment]
Seems like a permissions issue.

Have you tried / can you try running LeagueRecord as Administrator?
Are you by chance running League of Legends as Admin?

**Comment by J4nniK** [comment]
Running LeagueRecord as Admin seems to have fixed the issue but it is weird because I don't launch league as Admin.

**Comment by FFFFFFFXXXXXXX** [comment]
Yeah, thats strange. Atleast its working now!

I'll add a note to the readme in case someone else encounters this problem :)
