### ISSUE TITLE
Startup at Windows startup

### ISSUE THREAD

**Issue by natbrood** [FFFFFFFXXXXXXX/league_record#9]
Perhaps I'm reading over something, but it's not been implemented as a feature, I'd like to request this feature

**Comment by FFFFFFFXXXXXXX** [comment]
Just the basic autostart / start on windows login?
Sure I can add a setting for that, shouldn't be too much work.

**Comment by FFFFFFFXXXXXXX** [comment]
I've got a pre-release out now: <https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.15.0>
There is now an "autostart" setting that defaults to "false", so after the update you have to enable it in the settings.

Shoot me a comment if this is what you imagined the feature to do, then I'll close the issue and fully release the update.

**Comment by natbrood** [comment]
Woahh amazing, I installed the update. Will test and come back to you on this

**Comment by natbrood** [comment]
Works as expected, great work!

**Comment by natbrood** [comment]
I do seem to have found a bug. It opens up at boot now. It seems to work just fine, but it doesn't seem to record. Only after Quitting the application and them re-opening it, it will start to record things.

A bit of an oversight on my part, I should have been more thorough in my testing 😅

**Comment by FFFFFFFXXXXXXX** [comment]
Does this always happen or just sometimes?

**Comment by natbrood** [comment]
It seems to be quite consistent. I tested this at least 3 times now. Spread over several days on version 1.15

**Comment by FFFFFFFXXXXXXX** [comment]
alright, I'll look into it on the weekend

**Comment by FFFFFFFXXXXXXX** [comment]
Took me a while to figure out what went wrong. Heres the new release [v1.15.1](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.15.1).
